### ISSUE TITLE
npm run dist throws error

### ISSUE THREAD

**Issue by msal4** [kusti8/proton-native#115]
when running `npm run dist`  i get an error.
this is the complete log:
```powershell
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle anapp@0.0.1~predist: anapp@0.0.1
6 info lifecycle anapp@0.0.1~dist: anapp@0.0.1
7 verbose lifecycle anapp@0.0.1~dist: unsafe-perm in lifecycle true
8 verbose lifecycle anapp@0.0.1~dist: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\msal4\OneDrive\Desktop\anapp\node_modules\.bin;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\msal4\AppData\Local\atom\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Dart\dart-sdk\bin;C:\Users\msal4\AppData\Local\Android\Sdk\platform-tools;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\msal4\AppData\Local\Microsoft\WindowsApps;C:\Users\msal4\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\msal4\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle anapp@0.0.1~dist: CWD: C:\Users\msal4\OneDrive\Desktop\anapp
10 silly lifecycle anapp@0.0.1~dist: Args: [ '/d /s /c', 'electron-builder' ]
11 silly lifecycle anapp@0.0.1~dist: Returned: code: 1  signal: null
12 info lifecycle anapp@0.0.1~dist: Failed to exec dist script
13 verbose stack Error: anapp@0.0.1 dist: `electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid anapp@0.0.1
15 verbose cwd C:\Users\msal4\OneDrive\Desktop\anapp
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error anapp@0.0.1 dist: `electron-builder`
22 error Exit status 1
23 error Failed at the anapp@0.0.1 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kusti8** [comment]
The dist script is part of create-proton-app which uses electron-builder. It looks like electron-builder is not installed. I don't know why create-proton-app didn't do that for you. Try installing it.

**Comment by msal4** [comment]
I installed it but it looks like the windows platform is not supported
```powershell
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle anapp@0.0.1~predist: anapp@0.0.1
6 info lifecycle anapp@0.0.1~dist: anapp@0.0.1
7 verbose lifecycle anapp@0.0.1~dist: unsafe-perm in lifecycle true
8 verbose lifecycle anapp@0.0.1~dist: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\msal4\OneDrive\Desktop\anapp\node_modules\.bin;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\msal4\AppData\Local\atom\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Dart\dart-sdk\bin;C:\Users\msal4\AppData\Local\Android\Sdk\platform-tools;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\msal4\AppData\Local\Microsoft\WindowsApps;C:\Users\msal4\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\msal4\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle anapp@0.0.1~dist: CWD: C:\Users\msal4\OneDrive\Desktop\anapp
10 silly lifecycle anapp@0.0.1~dist: Args: [ '/d /s /c', 'electron-builder' ]
11 silly lifecycle anapp@0.0.1~dist: Returned: code: 1  signal: null
12 info lifecycle anapp@0.0.1~dist: Failed to exec dist script
13 verbose stack Error: anapp@0.0.1 dist: `electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid anapp@0.0.1
15 verbose cwd C:\Users\msal4\OneDrive\Desktop\anapp
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error anapp@0.0.1 dist: `electron-builder`
22 error Exit status 1
23 error Failed at the anapp@0.0.1 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kusti8** [comment]
Yeah windows support is coming soon.

**Comment by IceMimosa** [comment]
Can anyone help me？Thanks。

```shell
> npm run dist

> proton-app-test@0.0.1 dist /Users/icemimosa/Documents/github/AskMisa/proton-app-test
> electron-builder

  • electron-builder version=20.13.2
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=/Users/icemimosa/Documents/github/AskMisa/proton-app-test/package.json
  • author is missed in the package.json appPackageFile=/Users/icemimosa/Documents/github/AskMisa/proton-app-test/package.json
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 proton=8.3.0 appOutDir=dist/mac
TypeError: (0 , _fsExtraP(...).copyFile) is not a function
    at /Users/icemimosa/Documents/github/AskMisa/proton-app-test/node_modules/electron-builder-lib/src/ProtonFramework.ts:61:33
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at ProtonFramework.prepareMacosApplicationStageDirectory (/Users/icemimosa/Documents/github/AskMisa/proton-app-test/node_modules/electron-builder-lib/out/ProtonFramework.js:170:7)
    at /Users/icemimosa/Documents/github/AskMisa/proton-app-test/node_modules/electron-builder-lib/src/ProtonFramework.ts:90:11
    at Generator.next (<anonymous>)
    at deleteItem (/Users/icemimosa/Documents/github/AskMisa/proton-app-test/node_modules/fs-extra/lib/empty/index.js:20:25)
............
```

**Comment by kusti8** [comment]
Please report this with electron-builder.

**Comment by IceMimosa** [comment]
Upgrade node version to v8.11.1 fixes my problem. [electron-builder issue#2899](https://github.com/electron-userland/electron-builder/issues/2899)
