### ISSUE TITLE
Installation problem on linux. Missing libgtk-3-dev. 

### ISSUE THREAD

**Issue by lestard** [kusti8/proton-native#16]
When I tried to install proton-native with `npm i -S proton-native` like the quick-start guide suggests I got this error:

```
> npm i -S proton-native
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> libui-node@0.0.12 install /home/manuel/projekte/playground/proton-native/quickstart/node_modules/libui-node
> libui-download && autogypi && npm run build && npm run copy-node

Downloaded zip: /home/manuel/.libui/libui-shared-linux-x64-pre11.alpha.4.tar.gz
Libui binaries extracted to: /home/manuel/projekte/playground/proton-native/quickstart/node_modules/libui-node

> libui-node@0.0.12 build /home/manuel/projekte/playground/proton-native/quickstart/node_modules/libui-node
> node-gyp configure build

Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
gyp: Call to 'pkg-config gtk+-3.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-26-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/manuel/projekte/playground/proton-native/quickstart/node_modules/libui-node
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.0.12 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.0.12 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/manuel/.npm/_logs/2018-02-17T23_35_39_011Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open '/home/manuel/projekte/playground/proton-native/quickstart/package.json'
npm WARN quickstart No description
npm WARN quickstart No repository field.
npm WARN quickstart No README data
npm WARN quickstart No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.0.12 install: `libui-download && autogypi && npm run build && npm run copy-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.0.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/manuel/.npm/_logs/2018-02-17T23_35_39_612Z-debug.log
```

My machine has Linux Mint 18.3 installed which is based on ubuntu 16.04.
After some searching in the web I found out that I have to `sudo apt-get install build-essential libgtk-3-dev`. Now it works. Maybe you could add this info to the guide so that others can have an easier start with your framework. Maybe something like a preconditions paragraph?

**Comment by harisvsulaiman** [comment]
This is a given since libui depends on gtk3 on Linux.

**Comment by kusti8** [comment]
I will add this, but I'm really busy at the moment. If you have time you're free to submit a PR. Thanks.

**Comment by Coalpha** [comment]
Thank you! I've had this exact same error for awhile.
