### ISSUE TITLE
Unsupported platform "windows"?

### ISSUE THREAD

**Issue by Bizarrus** [kusti8/proton-native#166]
```
info@DESKTOP-B1MR61C MINGW64 ~/Documents/GitHub/RIDE
$ npm run dist

> RIDE@0.0.1 dist C:\Users\info\Documents\GitHub\RIDE
> electron-builder

  • electron-builder version=20.20.4
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=C:\Users\info\Documents\GitHub\RIDE\package.json
  • author is missed in the package.json appPackageFile=C:\Users\info\Documents\GitHub\RIDE\package.json
  • packaging       platform=win32 arch=x64 proton=10.6.0 appOutDir=dist\win-unpacked
Error: Unsupported platform: windows
    at C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\ProtonFramework.ts:115:10
    at Generator.next (<anonymous>)
    at deleteItem (C:\Users\info\Documents\GitHub\RIDE\node_modules\fs-extra\lib\empty\index.js:20:25)
    at fs.readdir (C:\Users\info\Documents\GitHub\RIDE\node_modules\fs-extra\lib\empty\index.js:16:5)
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at ProtonFramework.prepareApplicationStageDirectory (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\ProtonFramework.ts:117:6)
    at C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\platformPackager.ts:172:21
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doPack (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\platformPackager.ts:157:165)
    at C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\platformPackager.ts:110:95)
    at C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\packager.ts:369:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\info\Documents\GitHub\RIDE\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\info\Documents\GitHub\RIDE\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\packager.ts:337:39)
    at C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\packager.ts:313:52
From previous event:
    at Packager._build (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\packager.ts:290:133)
    at C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\packager.ts:286:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\packager.ts:243:14)
    at C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\src\index.ts:52:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder\src\builder.ts:224:10)
    at then (C:\Users\info\Documents\GitHub\RIDE\node_modules\electron-builder\src\cli\cli.ts:42:48)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! RIDE@0.0.1 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the RIDE@0.0.1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\info\AppData\Roaming\npm-cache\_logs\2018-07-13T23_07_03_783Z-debug.log

```

**Comment by mischnic** [comment]
No, electron-packager doesn't support Windows (yet - @develar ?)

**Comment by develar** [comment]
Ok, I guess it is a first user report and I need definitely finish support Windows.

**Comment by mischnic** [comment]
@nicostuhlfauth You could try using [launchui-packager](https://github.com/mimecorg/launchui-packager).
I've set up an example repo for proton-native: https://github.com/mischnic/proton-launchui

**Comment by nicostuhlfauth** [comment]
@mischnic Doesn't work for me with `create-proton-app`. Even the blank project throws a "Module did not self-register" error. Any idea?

**Comment by mischnic** [comment]
> Doesn't work for me with create-proton-app. Even the blank project throws a "Module did not self-register" error.

What do you mean by that? Please try cloning proton-launchui, copying your source files into the src folder and running `npm run package`.

**Comment by nicostuhlfauth** [comment]
Ah ok I got it running. Switched from the default build script that `create-proton-app` created to webpack with babel-loader. Thanks @mischnic 😄

**Comment by ateshuseyin** [comment]
windows 10
node: v8.12.0
npm: 6.4.1

the same problem :(

**Comment by icyJoseph** [comment]
I guess the windows support is not out yet? I am also getting the 
`Error: Unsupported platform: windows`,
error.

**Comment by mischnic** [comment]
Windows is now supported by electron-builder!
