### ISSUE TITLE
create-proton-app fails to create app

### ISSUE THREAD

**Issue by wildapt01** [kusti8/proton-native#177]
Environment: Linux Ubuntu 18.04 on Surface Book 2 (Custom kernel, based on 4.17), Node 10.8, fresh update/upgrade. libgtk-3-dev  and build-essential are in place. Python3 is in place.

Trying to create my app folder, but got the following errors (sorry, long!):
```
> node-gyp configure build


gyp
 
ERR! configure error 

gyp
 ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp 
ERR! stack     at PythonFinder.failNoPython (/home/patrick/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack
     at PythonFinder.<anonymous> (/home/patrick/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/patrick/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp
 ERR! stack     at E (/home/patrick/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR!
 stack     at /home/patrick/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack
     at /home/patrick/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/patrick/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp
 ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)

gyp
 ERR! System Linux 4.17.3-surface-linux-surface

gyp
 ERR! command "/home/patrick/.nvm/versions/node/v10.8.0/bin/node" "/home/patrick/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"

gyp ERR! cwd /home/patrick/mockingbird/node_modules/libui-node

gyp ERR! node -v v10.8.0
gyp
 ERR! node-gyp -v v3.7.0
gyp
 ERR! not ok 

npm ERR! 
code ELIFECYCLE

npm
 ERR! errno 1

npm ERR! libui-node@0.2.1 build: `node-gyp configure build`
npm
 ERR! Exit status 1
npm 
ERR! 
npm ERR! Failed at the libui-node@0.2.1 build script.
npm
 ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm WARN
 Local package.json exists, but node_modules missing, did you mean to install?



npm ERR! A complete log of this run can be found in:
npm ERR!     /home/patrick/.npm/_logs/2018-09-20T00_10_22_092Z-debug.log

npm 
WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN
 notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})



npm
 ERR! code ELIFECYCLE

npm
 ERR! errno 1

npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1

npm ERR! 
npm ERR!
 Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm
 ERR! A complete log of this run can be found in:
npm ERR!     /home/patrick/.npm/_logs/2018-09-20T00_10_22_390Z-debug.log


An error ocurred: 
 npm install has failed.
```

Any idea on how to fix it?

Thanks in advance.

**Comment by wildapt01** [comment]
```
whereis python ==>
python: /usr/bin/python3.6m /usr/bin/python3.6 /usr/lib/python2.7 /usr/lib/python3.6 /usr/lib/python3.7 /etc/python2.7 /etc/python3.6 /usr/local/lib/python3.6 /usr/include/python3.6m /usr/share/python
```

**Comment by kusti8** [comment]
I don't see a python 2.7 binary. You have the library path, but there's nothing in bin. Something is up with your distro.

**Comment by wildapt01** [comment]
Ok, I'll get into that a bit later. Thx a lot for your help!
