### ISSUE TITLE
Cannot run demo.js on mac

### ISSUE THREAD

**Issue by hugetiny** [kusti8/proton-native#192]
zhangzhechongs-Mac-Pro:proton-native zhangzhechong$ npm run demo

> proton-native@1.1.10 demo /Users/zhangzhechong/MacProjects/proton-native
> babel-node Demo.js

/Users/zhangzhechong/MacProjects/proton-native/node_modules/nbind/dist/nbind.js:15
        throw (err);
        ^

Error: Could not locate the bindings file. Tried:
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/build/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/build/Debug/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/build/Release/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/out/Debug/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/Debug/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/out/Release/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/Release/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/build/default/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/compiled/10.13.0/darwin/x64/nbind.node
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/build/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/build/Debug/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/build/Release/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/out/Debug/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/Debug/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/out/Release/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/Release/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/build/default/nbind.js
/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/compiled/10.13.0/darwin/x64/nbind.js
    at findCompiledModule (/Users/zhangzhechong/MacProjects/proton-native/node_modules/nbind/dist/nbind.js:83:15)
    at find (/Users/zhangzhechong/MacProjects/proton-native/node_modules/nbind/dist/nbind.js:93:13)
    at Object.init (/Users/zhangzhechong/MacProjects/proton-native/node_modules/nbind/dist/nbind.js:104:5)
    at Object.<anonymous> (/Users/zhangzhechong/MacProjects/proton-native/node_modules/libui-node/index.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/zhangzhechong/MacProjects/proton-native/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by mischnic** [comment]
Try deleting your node_modules folder and rerunning `npm install`

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
