### ISSUE TITLE
Error while installing dependencies of Notepad demo

### ISSUE THREAD

**Issue by dalisoft** [kusti8/proton-native#214]
Hello @kusti8.

Thanks for such great product. I am first time trying/starting desktop development with Proton-native as i'm always love performance and lightweight products/apps/libs.

But there error while starting the Notepad example.

OS: macOS 10.13.6
Node: v12
NPM: 6.9.0

```
> libui-node@0.2.1 install /Users/dalisoft/Downloads/proton-native-master/examples/Notepad/node_modules/libui-node
> libui-download && autogypi && npm run build

Downloaded zip: /Users/dalisoft/.libui/libui-shared-osx-x64-alpha3.5-master-008.tar.gz
Libui binaries extracted to: /Users/dalisoft/Downloads/proton-native-master/examples/Notepad/node_modules/libui-node

> libui-node@0.2.1 build /Users/dalisoft/Downloads/proton-native-master/examples/Notepad/node_modules/libui-node
> node-gyp configure build

  COPY Release/obj.target/nbind/geni/symbols.txt
  CXX(target) Release/obj.target/nbind/../nbind/src/common.o
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:139:8: warning: 'MarkIndependent' is deprecated: Weak
      objects are always considered independent. Use TracedGlobal when trying to use
      EmbedderHeapTracer. Use a strong handle when trying to keep an object alive.
      [-Wdeprecated-declarations]
                ref->MarkIndependent();
                     ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:563:3: note: 'MarkIndependent' has been
      explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:216:63: error: too few arguments to function call,
      single argument 'context' was not specified
                auto flags = static_cast<TypeFlags>(nanArgs[1]->Uint32Value());
                                                    ~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2567:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:71:
../../nbind/include/nbind/v8/BindWrapper.h:217:38: error: expected '(' for function-style cast or
      type construction
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                       ~~~~~~~~~~~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: no member named 'Handle' in namespace
      'v8'
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                            ~~~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:41: error: no member named 'Cast' in the global
      namespace
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                                    ~~^
../../nbind/include/nbind/v8/BindWrapper.h:217:19: error: 'handle_' is a private member of
      'node::ObjectWrap'
                void *ptr = v8::Handle<v8::External>::Cast(nanArgs[0])->Value();
                                ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/node_object_wrap.h:125:30: note: declared private
      here
  v8::Persistent<v8::Object> handle_;
                             ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:52:9: error: no matching member function for call to
      'ToObject'
                        arg->ToObject(),
                        ~~~~~^~~~~~~~
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable:
      requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable:
      requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:96:9: error: no matching member function for call to
      'ToObject'
                        arg->ToObject(),
                        ~~~~~^~~~~~~~
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable:
      requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable:
      requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:187:45: error: no matching member function for call to
      'BooleanValue'
DEFINE_NATIVE_BINDING_TYPE(bool, IsBoolean, BooleanValue, v8::Boolean);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:33: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~^~~~~~
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2559:8: note: candidate function not viable:
      requires single argument 'isolate', but no arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2562:51: note: candidate function not viable:
      requires single argument 'context', but no arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:189:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(double, IsNumber, NumberValue, v8::Number);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2564:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:190:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(float, IsNumber, NumberValue, v8::Number);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2564:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:192:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned int, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2567:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:193:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned short, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2567:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:194:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(unsigned char, IsNumber, Uint32Value, v8::Uint32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2567:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:196:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(signed int, IsNumber, Int32Value, v8::Int32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:197:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(signed short, IsNumber, Int32Value, v8::Int32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:198:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(signed char, IsNumber, Int32Value, v8::Int32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:72:
../../nbind/include/nbind/v8/BindingType.h:200:1: error: too few arguments to function call, single
      argument 'context' was not specified
DEFINE_NATIVE_BINDING_TYPE(char, IsNumber, Int32Value, v8::Int32);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nbind/include/nbind/v8/BindingType.h:173:40: note: expanded from macro
      'DEFINE_NATIVE_BINDING_TYPE'
                return(static_cast<Type>(arg->decode()));           \
                                         ~~~~~~~~~~~ ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2569:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:78:
../../nbind/include/nbind/v8/External.h:77:9: warning: 'MarkIndependent' is deprecated: Weak
      objects are always considered independent. Use TracedGlobal when trying to use
      EmbedderHeapTracer. Use a strong handle when trying to keep an object alive.
      [-Wdeprecated-declarations]
                        weak.MarkIndependent();
                             ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:563:3: note: 'MarkIndependent' has been
      explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:78:
../../nbind/include/nbind/v8/External.h:112:71: error: no matching member function for call to
      'ToObject'
        static inline Type fromWireType(WireType arg) { return(External(arg->ToObject())); }
                                                                        ~~~~~^~~~~~~~
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable:
      requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable:
      requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../../nbind/src/common.cc:4:
In file included from ../../nbind/include/nbind/nbind.h:8:
In file included from ../../nbind/include/nbind/noconflict.h:8:
In file included from ../../nbind/include/nbind/BindDefiner.h:11:
In file included from ../../nbind/include/nbind/api.h:80:
../../nbind/include/nbind/v8/BindingStd.h:128:28: error: no matching member function for call to
      'ToString'
                Nan::Utf8String val(arg->ToString());
                                    ~~~~~^~~~~~~~
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2528:44: note: candidate function not viable:
      requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/dalisoft/.node-gyp/12.1.0/include/node/v8.h:2544:35: note: candidate function not viable:
      requires single argument 'isolate', but no arguments were provided
                    Local<String> ToString(Isolate* isolate) const);
                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make: *** [Release/obj.target/nbind/../nbind/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/dalisoft/Downloads/proton-native-master/examples/Notepad/node_modules/libui-node
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dalisoft/.npm/_logs/2019-05-19T11_20_19_766Z-debug.log
npm WARN notepad@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dalisoft/.npm/_logs/2019-05-19T11_20_20_833Z-debug.log
dalisoft-MBP:Notepad dalisoft$ 
```

**Comment by dalisoft** [comment]
Can confirm, for other demos same thing 😞

**Comment by pcr910303** [comment]
@dalisoft I'm pretty sure that's because of node v12 😞
What about trying with node v11 or v10 as I has success with both?

**Comment by kusti8** [comment]
Yeah nbind only recently updated for node v12. https://github.com/charto/nbind/pull/130 but a new version has not been released yet. libui-node needs to be updated once that happens.

**Comment by dalisoft** [comment]
I tried with both node v10 and v11, also with v8 with `npx` via `npx -p node@VER npm i` or it's not works? I have projects with binaries which works only for node v10 and with this trick works good

**Comment by pcr910303** [comment]
@dalisoft Try using nvm... I'm not sure if `npx -p node@VER npm i` compiles addons based on the right version of NAPI.

**Comment by kusti8** [comment]
And it comes back with the same exact error for v10? Could you copy that log also?

**Comment by dalisoft** [comment]
@pcr910303 Thanks, i will try with `nvm` :)

We can close this issue as refers https://github.com/charto/nbind/pull/130

**Comment by dalisoft** [comment]
@kusti8 Yea, give me please some minutes

**Comment by dalisoft** [comment]
@kusti8 [Here](https://pastebin.com/uQ6qcCVA) log

**Comment by dalisoft** [comment]
@pcr910303 With `nvm` same thing with `node v10.15.3 (npm v6.4.1)`

**Comment by kusti8** [comment]
Proton Native V2 is now released! If the issue still occurs in the new update, please open a new issue.
