### ISSUE TITLE
can not `create-proton-app` in `Docker Desktop`

### ISSUE THREAD

**Issue by zaoqi** [kusti8/proton-native#221]
```
[libre@a01b6ed8e618 lab]$ npx create-proton-app proton-app
Creating a new Proton Native app on /Users/libre/builder-home/home/src/the-language/lab/proton-app

Installing packages... This may take a few minutes.

npm

WARN
 deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.


> libui-node@0.2.1 install /Users/libre/builder-home/home/src/the-language/lab/proton-app/node_modules/libui-node
> libui-download && autogypi && npm run build


Downloaded zip: /Users/libre/builder-home/home/.libui/libui-shared-linux-x64-alpha3.5-master-008.tar.gz

Libui binaries extracted to: /Users/libre/builder-home/home/src/the-language/lab/proton-app/node_modules/libui-node


> libui-node@0.2.1 build /Users/libre/builder-home/home/src/the-language/lab/proton-app/node_modules/libui-node
> node-gyp configure build


/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config gtk+-3.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp

gyp

ERR!

configure error


gyp
 ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:323:16)
gyp ERR!
stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp
 ERR! System Linux 4.9.184-linuxkit

gyp
ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR!
 cwd /Users/libre/builder-home/home/src/the-language/lab/proton-app/node_modules/libui-node
gyp ERR!
node -v v11.15.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok


npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! libui-node@0.2.1 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm

WARN Local package.json exists, but node_modules missing, did you mean to install?



npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/libre/builder-home/home/.npm/_logs/2019-08-08T07_58_05_126Z-debug.log

npm

WARN

optional
 SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):

npm

WARN

notsup
 SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})



npm

ERR!

code
 ELIFECYCLE

npm

ERR!

errno
 1

npm ERR! libui-node@0.2.1 install: `libui-download && autogypi && npm run build`
npm ERR!
 Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm

ERR!
 A complete log of this run can be found in:

npm

ERR!
     /Users/libre/builder-home/home/.npm/_logs/2019-08-08T07_58_18_169Z-debug.log


An error ocurred:
 npm install has failed.

```

**Comment by mischnic** [comment]
> /bin/sh: pkg-config: command not found

Are you using macOS or linux?

**Comment by zaoqi** [comment]
> > /bin/sh: pkg-config: command not found
> 
> Are you using macOS or linux?

I am using `Docker Desktop for Mac`

**Comment by mischnic** [comment]
So you're running this inside of a Docker container. As the error says, it seems like `pkg-config` isn't installed (use a package manager to install that package).

If you're trying to actually run an app using proton-native, then this won't work inside of the Docker VM (which can't access the macOS GUI)

**Comment by zaoqi** [comment]
I am trying to create and build/bundle an app
