### ISSUE TITLE
qt.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by sijpkes** [kusti8/proton-native#265]
I'm getting the following error after building the windows exe 

```dos
node-qt-napi\bindings\napi-v4\qt.node is not a valid Win32 application.
```

**Comment by kusti8** [comment]
Please provide more details. What's your code? What instructions hasve you followed? What's your directory structure? What commands have you run?

**Comment by estebanborai** [comment]
Hi! I found the same issue running the following commands:
```
# install the cli app
npx proton-native-cli init my-app
# move to your project directory
cd my-app

# run your app
npm run start
# OR to run with hot reloading
npm run dev
```
Source: [Proton Native - Quickstart](https://proton-native.js.org/#/quickstart)

```
> babel-node index.js

internal/modules/cjs/loader.js:1188
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\...\node_modules\node-qt-napi\bindings\napi-v4\qt.node is not a valid Win32 application.
\\?\C:\...\node_modules\node-qt-napi\bindings\napi-v4\qt.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.Module._load (C:\...\node_modules\proton-native\bin\utils\requireImpl.js:25:31)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\...\node_modules\node-qt-napi\lib\qt.js:9:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (C:\...\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

Environment:

OS: Windows 10
Arch: 64bits
Node Version: v12.18.0

Thanks in advance!

**Comment by dwdcth** [comment]
Duplicate of #
