### ISSUE TITLE
Errors when running npm start

### ISSUE THREAD

**Issue by jjgh** [kusti8/proton-native#267]
I'm new to proton-native and I followed the instructions at the following link in order to install Proton Native on Windows 10 and create my first app: https://www.techomoro.com/how-to-install-and-set-up-proton-native-on-windows-10/ 

The commands I ran without problems are:

```
npm install -g create-proton-app
create-proton-app awesome-project
```

Then when I run this last command:

```
cd awesome-project
npm start
```

it crashed with this info:

```
TypeError: (0 , _protonNative.render) is not a function
    at Object.<anonymous> (D:/dev/node.js-code/awesome-project/index.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at loader (D:\dev\node.js-code\awesome-project\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (D:\dev\node.js-code\awesome-project\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at Object.<anonymous> (D:\dev\node.js-code\awesome-project\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! awesome-project@0.0.1 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the awesome-project@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JFR\AppData\Roaming\npm-cache\_logs\2020-02-20T03_14_10_247Z-debug.log

```
and the debug log says:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\dev\\node.js\\node.exe',
1 verbose cli   'D:\\dev\\node.js\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle awesome-project@0.0.1~prestart: awesome-project@0.0.1
6 info lifecycle awesome-project@0.0.1~start: awesome-project@0.0.1
7 verbose lifecycle awesome-project@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle awesome-project@0.0.1~start: PATH [---FOR BREVITY I ONLY KEPT NPM RELATED PATH ITEMS---]: D:\dev\node.js\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\dev\node.js-code\awesome-project\node_modules\.bin;D:\dev\node.js\;C:\Users\JFR\AppData\Roaming\npm
9 verbose lifecycle awesome-project@0.0.1~start: CWD: D:\dev\node.js-code\awesome-project
10 silly lifecycle awesome-project@0.0.1~start: Args: [ '/d /s /c', 'babel-node index.js' ]
11 silly lifecycle awesome-project@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle awesome-project@0.0.1~start: Failed to exec start script
13 verbose stack Error: awesome-project@0.0.1 start: `babel-node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\dev\node.js\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (D:\dev\node.js\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid awesome-project@0.0.1
15 verbose cwd D:\dev\node.js-code\awesome-project
16 verbose Windows_NT 10.0.18362
17 verbose argv "D:\\dev\\node.js\\node.exe" "D:\\dev\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error awesome-project@0.0.1 start: `babel-node index.js`
22 error Exit status 1
23 error Failed at the awesome-project@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
My OS is Windows 10 and Node version is 12.16.0.

Can you help me understand what's going wrong?
Thanks!

**Comment by jjgh** [comment]
I also tried node versions 10.19.0 and 8.17.0 with no success (always getting the same error).

**Comment by kusti8** [comment]
The install method for Proton Native has changed. Please see here: https://proton-native.js.org/#/quickstart

**Comment by Lucia-Marcos** [comment]
Same error... :P

**Comment by kusti8** [comment]
The entire API has changed from V1 to V2. Install using the new method and see the updated documentation
