### ISSUE TITLE
Unable to start as per quickstart guide

### ISSUE THREAD

**Issue by y471n** [kusti8/proton-native#281]
**Describe the bug**
`npm run dev` and `npm run start` both result in error.

**To Reproduce**
Just followed the quickstart guide.

**Expected behavior**
Should run.

**Screenshots**
PFA.
![Screenshot 2020-04-17 at 9 39 03 AM](https://user-images.githubusercontent.com/2056046/79531318-93688280-808f-11ea-9b0a-6457ba37ee98.png)

**Versions:**
 - OS: Mac
 - Version 10.15.4
 - Node version: 12.12.0

**Additional context**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/ym/.nvm/versions/node/v12.12.0/bin/node',
1 verbose cli   '/Users/ym/.nvm/versions/node/v12.12.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-app@0.0.1~prestart: my-app@0.0.1
6 info lifecycle my-app@0.0.1~start: my-app@0.0.1
7 verbose lifecycle my-app@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle my-app@0.0.1~start: PATH: /Users/ym/.nvm/versions/node/v12.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ym/code/proton/my-app/node_modules/.bin:/Users/ym/.nvm/versions/node/v12.12.0/bin:/Users/ym/Downloads/google-cloud-sdk 2/bin:/Users/ym/.nvm/versions/node/v12.14.1/bin:/Users/ym/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ym/Downloads/google-cloud-sdk 2/bin:/Users/ym/.nvm/versions/node/v12.14.1/bin:/Users/ym/.local/bin:/Users/ym/Library/Android/platform-tools:/Users/ym/Library/Android/platform-tools
9 verbose lifecycle my-app@0.0.1~start: CWD: /Users/ym/code/proton/my-app
10 silly lifecycle my-app@0.0.1~start: Args: [ '-c', 'babel-node index.js' ]
11 silly lifecycle my-app@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle my-app@0.0.1~start: Failed to exec start script
13 verbose stack Error: my-app@0.0.1 start: `babel-node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/ym/.nvm/versions/node/v12.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/Users/ym/.nvm/versions/node/v12.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid my-app@0.0.1
15 verbose cwd /Users/ym/code/proton/my-app
16 verbose Darwin 19.4.0
17 verbose argv "/Users/ym/.nvm/versions/node/v12.12.0/bin/node" "/Users/ym/.nvm/versions/node/v12.12.0/bin/npm" "run" "start"
18 verbose node v12.12.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error my-app@0.0.1 start: `babel-node index.js`
22 error Exit status 1
23 error Failed at the my-app@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Above is error log.

**Comment by dansiemens** [comment]
Try deleting `node_modules` and running `npm install`

**Comment by y471n** [comment]
Thanks. This worked!
