### ISSUE TITLE
Need to update install instructions

### ISSUE THREAD

**Issue by ElonVolo** [kusti8/proton-native#290]
**Link to the page**

**Quote of Error**
On the instruction page, there's a directions that one needs to install

qtbase5-dev

When I installed this package on a fresh, stock install of Ubuntu, I got the message "could not find a Qt installation of ''".

I looked for the error in Stackoverflow and found that also running the command

**sudo apt-get install qt5-default**

seemed to fix this problem.

**Proposed changes**

 I would suggest adding the qt5-default it to the documentation, as well as doing a double check with a clean install of Ubuntu just to make sure there's no additional dependencies missing in the docs. I'm guessing that the devs on this project already had a lot of the qt infrastructure set up on their machines, and a few stray dependencies they forgot were needed might have gotten past the docs.

One other suggestion, I think a lot of people, including myself, would be installing this for Ubuntu, so perhaps a

**sudo apt-get install qtbase5-dev**
**sudio apt-get install qt5-default** 

Would be useful in a "Installing for Ubuntu" section.

**Comment by TheRafaelFarias** [comment]
Im trying to start a new project with proton native, but when i execute the command

Im getting this error 

` > npx proton-native-cli init Creator
npx: instalou 45 em 13.866s
Creating a new Proton Native app on /home/rafael/dev/pratice/Creator

Installing packages... This may take a few minutes. 


> node-qt-napi@0.0.3 install /home/rafael/dev/pratice/Creator/node_modules/node-qt-napi
> cross-env JOBS=max node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for node-qt-napi@0.0.3 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Remote end closed socket abruptly. 
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l Qt5Core Qt5Gui Qt5Widgets' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/rafael/.asdf/installs/nodejs/12.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-51-generic
gyp ERR! command "/home/rafael/.asdf/installs/nodejs/12.16.3/bin/node" "/home/rafael/.asdf/installs/nodejs/12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/rafael/dev/pratice/Creator/node_modules/node-qt-napi/bindings/napi-v4/qt.node" "--module_name=qt" "--module_path=/home/rafael/dev/pratice/Creator/node_modules/node-qt-napi/bindings/napi-v4" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=4" "--node_napi_label=napi-v4"
gyp ERR! cwd /home/rafael/dev/pratice/Creator/node_modules/node-qt-napi
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/rafael/.asdf/installs/nodejs/12.16.3/bin/node /home/rafael/.asdf/installs/nodejs/12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/rafael/dev/pratice/Creator/node_modules/node-qt-napi/bindings/napi-v4/qt.node --module_name=qt --module_path=/home/rafael/dev/pratice/Creator/node_modules/node-qt-napi/bindings/napi-v4 --napi_version=5 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/rafael/dev/pratice/Creator/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.3.0-51-generic
node-pre-gyp ERR! command "/home/rafael/.asdf/installs/nodejs/12.16.3/bin/node" "/home/rafael/dev/pratice/Creator/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/rafael/dev/pratice/Creator/node_modules/node-qt-napi
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/rafael/.asdf/installs/nodejs/12.16.3/bin/node /home/rafael/.asdf/installs/nodejs/12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/rafael/dev/pratice/Creator/node_modules/node-qt-napi/bindings/napi-v4/qt.node --module_name=qt --module_path=/home/rafael/dev/pratice/Creator/node_modules/node-qt-napi/bindings/napi-v4 --napi_version=5 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-qt-napi@0.0.3 install: `cross-env JOBS=max node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-qt-napi@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rafael/.npm/_logs/2020-05-15T17_11_33_605Z-debug.log`
