### ISSUE TITLE
Unable to create a Proton-Native App in Raspberry Pi 4B

### ISSUE THREAD

**Issue by shibichakkaravarthy** [kusti8/proton-native#317]
I am trying to create an Touch Interface that can control Electric Appliances in out Home with Raspberry Pi 4B single-board ARM based computer. Since I'm a react native developer, I choose Proton-Native rather than python. But I was unable to create the App. There was some error regarding the node-qt-napi but I was able to create an App in macOS without any issue. Please help me with this. Here is the whole output from the Terminal...

`**pi@raspberrypi:~ $ npx proton-native-cli init MyApp
npx: installed 92 in 13.429s
Creating a new Proton Native app on /home/pi/MyApp

Installing packages... This may take a few minutes. 

> node-qt-napi@0.0.3 install /home/pi/MyApp/node_modules/node-qt-napi
> cross-env JOBS=max node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kusti8/node-qt-napi/releases/download/0.0.3/qt-v0.0.3-4-linux-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-qt-napi@0.0.3 and node@14.15.2 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
Package Qt5Core was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Core.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Core' found
Package Qt5Gui was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Gui.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Gui' found
Package Qt5Widgets was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Widgets.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Widgets' found
gyp: Call to 'pkg-config --libs-only-l Qt5Core Qt5Gui Qt5Widgets' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.79-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MyApp/node_modules/node-qt-napi/bindings/napi-v4/qt.node" "--module_name=qt" "--module_path=/home/pi/MyApp/node_modules/node-qt-napi/bindings/napi-v4" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=4" "--node_napi_label=napi-v4"
gyp ERR! cwd /home/pi/MyApp/node_modules/node-qt-napi
gyp ERR! node -v v14.15.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MyApp/node_modules/node-qt-napi/bindings/napi-v4/qt.node --module_name=qt --module_path=/home/pi/MyApp/node_modules/node-qt-napi/bindings/napi-v4 --napi_version=7 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MyApp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.79-v7l+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/MyApp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/MyApp/node_modules/node-qt-napi
node-pre-gyp ERR! node -v v14.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MyApp/node_modules/node-qt-napi/bindings/napi-v4/qt.node --module_name=qt --module_path=/home/pi/MyApp/node_modules/node-qt-napi/bindings/napi-v4 --napi_version=7 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-qt-napi@0.0.3 install: `cross-env JOBS=max node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-qt-napi@0.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-12-25T18_01_05_645Z-debug.log**
`

**Comment by shibichakkaravarthy** [comment]
Any update on this?

**Comment by misaeldossantos** [comment]
maybe you need add PKG_CONFIG_PATH to environment variable with the directory where you installed qt

**Comment by Diana0604** [comment]
You need to install qt in the raspberry before hand. I followed [these instructions](https://qengineering.eu/install-qt5-with-opencv-on-raspberry-pi-4.html).
