### ISSUE TITLE
Linux GTK error still persisting even after installing gtk package

### ISSUE THREAD

**Issue by TristanWiley** [kusti8/proton-native#36]
I've referenced #16 regarding the GTK requirement and have it installed. However, the error I'm getting is still persisting. 

In this I'm using create-proton-app although it occurs even when using just npm install

```
Creating a new Proton Native app on /home/tristan/ProtonDemo

Installing packages... Make take a few minutes.


> libui-node@0.0.12 install /home/tristan/ProtonDemo/node_modules/libui-node
> libui-download && autogypi && npm run build && npm run copy-node

Downloaded zip: /home/tristan/.libui/libui-shared-linux-x64-pre11.alpha.4.tar.gz
Libui binaries extracted to: /home/tristan/ProtonDemo/node_modules/libui-node

> libui-node@0.0.12 build /home/tristan/ProtonDemo/node_modules/libui-node
> node-gyp configure build

Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
gyp: Call to 'pkg-config gtk+-3.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/tristan/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/home/tristan/.nvm/versions/node/v8.8.1/bin/node" "/home/tristan/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/tristan/ProtonDemo/node_modules/libui-node
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.0.12 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.0.12 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tristan/.npm/_logs/2018-02-27T16_01_47_970Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.0.12 install: `libui-download && autogypi && npm run build && npm run copy-node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.0.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tristan/.npm/_logs/2018-02-27T16_01_48_356Z-debug.log

An error ocurred:
 npm install --save --loglevel error proton-native has failed.
```

**Comment by kusti8** [comment]
What is the exact name of the package you installed?

**Comment by TristanWiley** [comment]
`build-essential` and `libgtk-3-dev`
One was already installed

**Comment by albe-rosado** [comment]
@TristanWiley which distro are you using?

**Comment by TristanWiley** [comment]
Elementary OS, aka Ubuntu 14.04

**Comment by albe-rosado** [comment]
@TristanWiley  check you have: `build-essential  (12.4ubuntu1)` and `libgtk-3-dev (3.22.25-0ubuntu0.1)` installed while I install elementary to try to reproduce the bug.

**Comment by albe-rosado** [comment]
![virtualbox_elem_27_02_2018_19_59_02](https://user-images.githubusercontent.com/18025582/36764030-b0b35886-1bf8-11e8-8c8a-820138d3a630.png)
this was a fresh install of the last version of elementaryOS. Just installed libgtk-3-dev and node v8 and no problem so far.

**Comment by TristanWiley** [comment]
Hmm. I'll spend some more time debugging. Thanks for testing!

**Comment by albe-rosado** [comment]
@TristanWiley did you were able to get it working? try with `create-proton-app` cli, otherwise I think this issue should be closed if the problem isn't related to Proton Native.

**Comment by TristanWiley** [comment]
I haven't gotten it working yet. I've tried with the CPA cli and it was the same issue. I'll figure it out eventually and report back. 

Some setup issue I presume.

**Comment by TristanWiley** [comment]
Looks like it was missing from my PATH.

`export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig`

Fixed it :+1:
