### ISSUE TITLE
NPM install fails on Windows 10, Node 10

### ISSUE THREAD

**Issue by matiit** [kusti8/proton-native#88]
```
λ create-proton-app test-proton-app
Creating a new Proton Native app on C:\Users\matiq\home\sandbox\test-proton-app

Installing packages... This may take a few minutes.


An error ocurred:
 npm.cmd install --save --loglevel error proton-native has failed.

(node:17644) UnhandledPromiseRejectionWarning: Error: [object Object]
    at isOnline.then.then.then.catch (C:\Users\matiq\AppData\Roaming\npm\node_modules\create-proton-app\src\createApp.js:95:11)
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:17644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
λ node -v
v10.0.0
```

```
λ npm -v
5.6.0
```

![image](https://user-images.githubusercontent.com/138194/39540289-1f923880-4e3a-11e8-87a1-044af22fbf79.png)

**Comment by mischnic** [comment]
@albe-rosado

**Comment by matiit** [comment]
Reinstalling `proton-native` didn't help. 

The `windows-build-tools` package was not installed on my system, installing it now and will try reinstalling `proton-native` then.

**Comment by albe-rosado** [comment]
@jakubtuchol  did installing windows-build-tools worked for you?

**Comment by albe-rosado** [comment]
i meant oh, that was the macOS person lol.... that is weird, i do have a mac , let me try

**Comment by madongo** [comment]
I just tried installing this on mac and got the same error:
`    at <anonymous>
(node:22653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22653) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by albe-rosado** [comment]
Also, we should move this to `create-proton-app` repo, this is not  proton-native related, can anyone reopen the issue over there, with details? @mischnic  can you reproduce it?

**Comment by mischnic** [comment]
@albe-rosado 

No problem with macOS Sierra. And in the first comment I made here, I pointed out that your code might hide the real error which got thrown somewhere unexpectedly

**Comment by albe-rosado** [comment]
you are right!, let me update that

**Comment by madongo** [comment]
Hey I am on Mac
Node - v9.5.0
High Sierra - 10.13.3 (17D47)
I tried it with node v10 and I am not having any luck either

**Comment by albe-rosado** [comment]
@mischnic actually, I just looked at the code,`erroMessage` is a string, so you won't get [object Object]. Although I would like to print the stdout/stderr to give a better idea to the developer what went wrong, will do that.

**Comment by albe-rosado** [comment]
@madongo @jakubtuchol  a new version is up, please update to create-proton-app@1.1.5

**Comment by albe-rosado** [comment]
you will get better logging, so we will be able to know what happended on your enviroment. :)

**Comment by jakubtuchol** [comment]
@albe-rosado I didn't have to install `windows-build-tools`, but I was able to verify that `create-proton-app` was able to work successfully. Thanks so much!

**Comment by iamwelk** [comment]
I have the same error..

**Comment by albe-rosado** [comment]
@iamwelk do you have create-proton-app@1.1.5? can you share the logs?
